### ISSUE TITLE
Free variable

### ISSUE THREAD

**Issue by ZoltanOnody** [FMFI-UK-1-AIN-412/elm-formula#3]
Ked dam free `freeFormula` na formule `a` cakal by som, ze mi to vrati `{a}`. Ono mi to vsak vrati prazdny set. Kedze premenna `a` nieje viazana ziadnym kvantifikatorom, cakal by som, ze je volna.

Ide o bug alebo o nejaku feature ktorej nechapem?

Well, ide skor o to, ze ak sparsujem `a` dostanem `Ok (Atom "a" [])` a teda https://github.com/FMFI-UK-1-AIN-412/elm-formula/blob/master/src/Formula.elm#L159 tu premennu `a` zahodim. 

Podla mna by tam malo byt nieco ako 
```
Atom var ts ->
  case ts of 
    [] -> Set.insert var fvs
    _ -> List.foldl freeTermA fvs ts
 ```

@crnkjck @yoyko chapem tomu spravne alebo sa mylim?

PS: preco sa to vola `freeFormula` a nie `freeVariables`?

**Comment by ZoltanOnody** [comment]
![image](https://user-images.githubusercontent.com/1943747/38777545-10e66970-40aa-11e8-8d0e-c095f4d446f2.png)

Cakal by som, ze 4 a 5ka budu nevalidne a 6ka bude validna.

**Comment by crnkjck** [comment]
Toto spravanie je z mojho hladiska ocakavane a viac-menej v poriadku.

Samotne <var>a</var> je atomicka formula, ktora sa sklada z predikatoveho symbolu <var>a</var> a jeho 0 argumentov, ktore nie su uzatvorkovane. Cize je to nieco ako vyrokova premenna. Jej vyznamom je pravdivostna hodnota.

V f(<var>a</var>) (4) je pouzitie <var>a</var> v poriadku, pretoze tu <var>a</var> vystupuje ako *individuova* premenna, teda premenna, ktorej hodnotou je individuum – objekt z domeny, nie pravdivostna hodnota. Ako individuova premenna sa <var>a</var> este v dokaze nevyskytlo.

Predikatove symboly s 0 argumentmi parser akceptuje, pretoze som chcel, aby sa prvoradovy tablovac dal pouzit aj ako vyrokovologicky.

Samozrejme, bolo by dobre, keby parser (alebo nejaky postprocessing) vedel o tom, ktore mena sa doteraz pouzili na aky ucel a nedovoloval pouzit to iste meno (<var>a</var>) ako premennu aj ako predikatovy symbol (pripadne robit este matucejsie veci, napriklad pouzit <var>a</var> ako predikatovy symbol s roznymi aritami na roznych miestach). Nema to ale IMHO velku prioritu.

**Comment by crnkjck** [comment]
Nazov funkcie `freeFormula` chce znamenat volne premenne formuly (nie je to gramaticky spravne, ale ani o to neslo). V module je aj `freeTerm` (volne premenne termu). Kedze v elme sa funkcie nedaju overloadovat, nejak bolo treba tieto dve odlisit.

**Comment by ZoltanOnody** [comment]
Jasne chapem, dakujem. Tuto issue teda zatvorim.
